
DEBUG=False

SQLALCHEMY_DATABASE_URI = 'mysql://user:password@localhost/dbname'
SQLALCHEMY_TRACK_MODIFICATIONS = True
SQLALCHEMY_ECHO = False

MAIL_SUPPRESS_SEND = False
MAIL_SERVER=''  # change this to server config needed
MAIL_PORT=25,
MAIL_USE_SSL=False,
MAIL_USERNAME = ''
MAIL_PASSWORD = ''


TWEEPY_CONSUMER_KEY = ''
TWEEPY_CONSUMER_SECRET = ''
TWEEPY_ACCESS_TOKEN_KEY = ''
TWEEPY_ACCESS_TOKEN_SECRET = ''

GITHUB_CLIENT_ID=''
GITHUB_CLIENT_SECRET=''
PYGITHUB_DEBUG=False


SLACK_TEST_TOKEN = ''
SLACK_CLIENT_ID = ''
SLACK_CLIENT_SECRET = ''
